/*
 * Copyright (c) 2025 Ivan Zhukov. All Rights Reserved.
 * Email: ivzhuk7@gmail.com
 */

#pragma once

#include "Runtime/Launch/Resources/Version.h"

#define UNREALDRIVE_MAJOR_VERSION	1
#define UNREALDRIVE_MINOR_VERSION	0
#define UNREALDRIVE_PATCH_VERSION	2

#if defined(UNREALDRIVE_PIPLINE_VERSION)
#define UNREALDRIVE_VERSION_STRING \
	VERSION_STRINGIFY(UNREALDRIVE_MAJOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(UNREALDRIVE_MINOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(UNREALDRIVE_PATCH_VERSION) \
	VERSION_TEXT("-") \
	VERSION_STRINGIFY(UNREALDRIVE_PIPLINE_VERSION)
#else
#define UNREALDRIVE_VERSION_STRING \
	VERSION_STRINGIFY(UNREALDRIVE_MAJOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(UNREALDRIVE_MINOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(UNREALDRIVE_PATCH_VERSION)
#endif
